version: '2'
services:
  server:
    container_name: "api-server"
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/code:/code
  simplehttp:
    container_name: "simple-http-client"
    build: ./simple-http
    ports:
      - "8001:80"
    volumes:
      - ./simple-http/code:/usr/local/apache2/htdocs
